### PR TITLE
EventsLoader.h: fix building

### PR DESCRIPTION
**Pull request by manio**
This commit is fixing build the project. The error was:
In file included from /usr/src/bluecherry-client/src/event/EventsLoader.cpp:18:
/usr/src/bluecherry-client/src/event/EventsLoader.h:23:10: fatal error: src/server/DVRServer.h: No such file or directory

### CODE REVIEW

**Comment by manio** [comment]
Offtopic question to @antonsviridenko:
Did you mabye complete porting to Qt5? Or the stage is as in the master currently?

**Comment by antonsviridenko** [comment]
Hello @manio 
I think it is more reasonable to check why the top level source directory is not present in include path in your build environment. Or at least include headers relative to src/ subdirectory. I.e. 
`#include "server/DVRServer.h"`
looks nicer than
`#include "../server/DVRServer.h"`

**Comment by antonsviridenko** [comment]
>Did you mabye complete porting to Qt5? Or the stage is as in the master currently?

Stage is as in the master. Current show stopper is the QML code and C++ code  that loads it, there are some significant differences between Qt4 and Qt5.

**Comment by manio** [comment]
Thanks for the info.
No idea why the src is not in include path. I am just compiling it out of the box, with all settings default using qt4.8.7-31 and cmake 3.17.1-2...
But your suggestion also did the trick and it is compiling fine, so I amended the commit.

**Pull request merged**
