### PR TITLE
Done #263, added switching between layouts and cameras inside layout …

### PR DESCRIPTION
**Pull request by AlexanderAgd**
…by arrow keys

### CODE REVIEW

**Comment by AlexanderAgd** [comment]
Up & Down keys switches layout, and Left & Right switches cameras inside selected layout, one time press Up or Down you back to the selected layout, easy and conveniently

**Comment by AlexanderAgd** [comment]
Keys changed  - for layouts its PageUp & PageDown, for cameras inside layout  its  <  >

**Comment by jasauders** [comment]
Hi there, Alexander. While this is a great addition that I would put to use, I find myself curious about the choice of page up/page down. Reason I mention this is I've ran into a number of laptops that lack the page up/page down keys. Thanks for your time!

**Comment by antonsviridenko** [comment]
Hi Jason,

we wanted to use arrow keys first, but they are used for controlling PTZ camera movements, so these keys were selected. You can propose some better solution, we are open to suggestions

@jasauders

**Comment by jasauders** [comment]
Full disclosure: I'm not a Mac user, but I had Macbooks in mind as I commented above thinking the choice of page up/down might exclude Macbook users. After some digging it seems as if Macbooks utilize Fn+up/down for that functionality. Apologies. :)

**Pull request merged**
