### PR TITLE
Fix drag&drop event adding camera

### PR DESCRIPTION
**Pull request by trongthanhqvo**
I tested your new implementing and there are a few minor bugs.
1. setPixmap image with currentFrame when the drag camera on LiveViewWindow layout
2. drag&drop event for adding camera is auto camera index with grid

Here is my fix:
1. scale size change image with widget
2. add camera at drop position

### CODE REVIEW

**Comment by antonsviridenko** [comment]
Can you provide more detailed explanation what issues this PR is supposed to fix?
First part, as I understand, image attached to drag&drop mouse cursor looks too big and you want to scale it down. Does it cause any issues, if so, can you show some screenshot that demonstrate this issue?

**Comment by trongthanhqvo** [comment]
yes, that's my opinion too.
And drag&drop event for adding camera is auto, I think adding camera at drop position mouse cursor which is more convenient for end user.

**Comment by antonsviridenko** [comment]
Hi @trongthanhqvo 

sorry for delayed response,
I've fixed the first issue in this commit
https://github.com/bluecherrydvr/bluecherry-client/commit/c54341458ecd9a95048a74ac8aa656b1c61426e3
about the second one, your implementation replaces existing camera if there is an active camera in a drop target area,
this is not acceptable, camera should be added, not replaced

**Comment by trongthanhqvo** [comment]
Thanks for that change @antonsviridenko.

The second one, I see you also implemented that event in the previous version.

**Pull request closed without merging**
